# Generated by Django 3.0.4 on 2020-03-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caractproducto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristica',
            name='codigoP',
            field=models.CharField(default=2, max_length=50, verbose_name='Codigo'),
            preserve_default=False,
        ),
    ]
