# Generated by Django 3.0.4 on 2020-03-16 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidadMedida', '0001_initial'),
        ('caractproducto', '0002_caracteristica_codigop'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristica',
            name='UMedida',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='unidadMedida.UnidadM', verbose_name='Unidad de medida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='cantidad',
            field=models.IntegerField(default=2, verbose_name='Disponibles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='disponibilidad',
            field=models.CharField(default=2, max_length=50, verbose_name='precio promo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='precio',
            field=models.CharField(default=2, max_length=50, verbose_name='Precio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='precioPromo',
            field=models.CharField(default=2, max_length=50, verbose_name='precio promo'),
            preserve_default=False,
        ),
    ]
