# Generated by Django 3.0.4 on 2020-03-16 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caractproducto', '0003_auto_20200315_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caracteristica',
            name='disponibilidad',
        ),
    ]
