# Generated by Django 3.0.4 on 2020-03-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caractproducto', '0004_remove_caracteristica_disponibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica',
            name='precioPromo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='precio promo'),
        ),
    ]
