# Generated by Django 3.0.4 on 2020-03-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caractproducto', '0006_caracteristica_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica',
            name='minimo',
            field=models.IntegerField(verbose_name='Pedido minimo'),
        ),
    ]
