# Generated by Django 3.0.4 on 2020-03-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caractproducto', '0007_auto_20200317_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristica',
            name='entero',
            field=models.IntegerField(default=2, verbose_name='Entero prueba'),
            preserve_default=False,
        ),
    ]
