# Generated by Django 3.0.4 on 2020-05-03 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caractproducto', '0009_auto_20200317_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caracteristica',
            old_name='cantidad',
            new_name='existencia',
        ),
    ]
