# Generated by Django 3.0.4 on 2020-05-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caractproducto', '0010_auto_20200503_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caracteristica',
            old_name='existencia',
            new_name='cantidad',
        ),
    ]
