language: python
python:
  - "3.8"
env:
    -PATH=\Users\aiori\AppData\Local\Programs\Python\Python38\python.exe -m venv env
services:
  -postgresql
install:
  - pip install
  - pip install -r requirements.txt
script:
  - python manage.py test