# Generated by Django 3.0.4 on 2020-03-16 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Image', verbose_name='Imagen')),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='servicios.Servicio')),
            ],
        ),
    ]
