# Generated by Django 3.0.4 on 2020-03-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='content',
            field=models.TextField(max_length=500, verbose_name='Contenido'),
        ),
    ]
