# Generated by Django 3.0.4 on 2020-05-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20200316_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='image',
            field=models.ImageField(default=2, upload_to='servicios', verbose_name='Imagen de fondo'),
            preserve_default=False,
        ),
    ]
