# Generated by Django 3.0.4 on 2020-03-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryProducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='image',
            field=models.ImageField(upload_to='ImagenesProducto', verbose_name='Imagen'),
        ),
    ]
