# Generated by Django 3.0.4 on 2020-03-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=2, upload_to='productos', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
