# Generated by Django 3.0.4 on 2020-03-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20200312_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=2, verbose_name='Disponibles'),
            preserve_default=False,
        ),
    ]
