# Generated by Django 3.0.4 on 2020-03-16 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidadMedida', '0001_initial'),
        ('productos', '0004_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='UMedida',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='unidadMedida.UnidadM', verbose_name='Unidad de medida'),
            preserve_default=False,
        ),
    ]
