# Generated by Django 3.0.4 on 2020-03-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_umedida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='valorpromo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Precio Promocion'),
        ),
    ]
