# Generated by Django 3.0.4 on 2020-03-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20200315_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo',
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default=2, max_length=100, verbose_name='Nombre del producto'),
            preserve_default=False,
        ),
    ]
