# Generated by Django 3.0.4 on 2020-03-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_remove_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nuevoProducto',
            field=models.BooleanField(blank=True, null=True, verbose_name='Nuevo'),
        ),
    ]
