# Generated by Django 3.0.4 on 2020-04-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_producto_nuevoproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='nuevoProducto',
        ),
        migrations.AddField(
            model_name='producto',
            name='promocion',
            field=models.BooleanField(blank=True, null=True, verbose_name='Promocion'),
        ),
    ]
