# Generated by Django 3.0.4 on 2020-05-25 23:31

from django.db import migrations, models
import orders.utils


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200507_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_no',
            field=models.CharField(blank=True, default=orders.utils.create_new_ref_number, max_length=500, null=True),
        ),
    ]
