# Generated by Django 3.0.4 on 2020-05-25 23:51

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200525_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_no',
            field=models.CharField(blank=True, default=orders.models.increment_invoice_number, max_length=500, null=True),
        ),
    ]
