# Generated by Django 3.0.4 on 2020-05-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200525_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
