# Generated by Django 3.0.4 on 2020-05-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200526_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
