# Generated by Django 3.0.4 on 2020-05-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200526_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
