# Generated by Django 3.0.4 on 2020-06-05 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200526_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
