# Generated by Django 3.0.4 on 2020-06-05 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='published',
            new_name='fecha',
        ),
    ]
