# Generated by Django 3.0.4 on 2020-06-25 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200624_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='datos',
        ),
    ]
