# Generated by Django 3.0.4 on 2020-06-25 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dastosUsuario', '0006_auto_20200519_2115'),
        ('orders', '0018_remove_order_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datos',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dastosUsuario.Datos', verbose_name='Datos'),
            preserve_default=False,
        ),
    ]
