# Generated by Django 3.0.4 on 2020-06-25 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_datos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='datos',
            new_name='direccion',
        ),
    ]
