# Generated by Django 3.0.4 on 2020-06-25 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dastosUsuario', '0006_auto_20200519_2115'),
        ('orders', '0020_auto_20200624_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dastosUsuario.Datos'),
        ),
    ]
