# Generated by Django 3.0.4 on 2020-06-25 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dastosUsuario', '0006_auto_20200519_2115'),
        ('orders', '0023_auto_20200624_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dastosUsuario.Datos'),
        ),
    ]
