# Generated by Django 3.0.4 on 2020-06-25 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20200624_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='direccion',
        ),
    ]
