# Generated by Django 3.0.4 on 2020-08-06 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dastosUsuario', '0006_auto_20200519_2115'),
        ('orders', '0026_remove_order_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='direccion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dastosUsuario.Datos'),
            preserve_default=False,
        ),
    ]
