# Generated by Django 3.0.4 on 2020-05-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orientacion',
            options={'ordering': ['-id'], 'verbose_name': 'Orientacion', 'verbose_name_plural': 'Orientacions'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='imagenfondo',
            field=models.ImageField(upload_to='Imagenfondo', verbose_name='Imagenfondo'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='imagenfrontal',
            field=models.ImageField(upload_to='Imagenfrontal', verbose_name='Imagenfrontal'),
        ),
    ]
