# Generated by Django 3.0.4 on 2020-05-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_auto_20200505_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Subtitulo'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Titulo'),
        ),
    ]
