# Generated by Django 3.0.4 on 2020-05-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_auto_20200505_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='imagenfondo',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenfondo', verbose_name='Imagenfondo'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='imagenfrontal',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenfrontal', verbose_name='Imagenfrontal'),
        ),
    ]
